# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enuda_mag', '0004_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
